repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: local
    hooks:
      - id: no-utcnow
        name: Disallow datetime.utcnow()
        entry: python tools/check_utcnow.py
        language: system
        types: [python]
        stages: [commit]
      - id: pytest
        name: Run pytest
        entry: pytest -q
        language: system
        stages: [pre-push]
