"""
Integration tests for sanitizer working with exporter.
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from bulletin_builder.app_core.sanitize import sanitize_email_html


def test_sanitizer_integration():
    """Test that sanitizer integrates properly with the email copy process."""

    # Simulate the HTML that would be generated by the renderer
    test_html = '''<html>
<head><title>Test Bulletin</title></head>
<body>
<h1>Test Bulletin</h1>
<p>This is a <a href="#" style="margin:10px;">test link</a> with bad styles.</p>
<table style="border-collapse:separate;">
<tr><td style="border:1px solid black;">Cell content</td></tr>
</table>
</body>
</html>'''

    # Apply the same transformation as in the exporter
    from premailer import transform
    transformed_html = transform(test_html)

    # Apply sanitizer as done in exporter
    sanitized_html = sanitize_email_html(transformed_html)

    # Verify sanitizer was applied correctly
    assert 'style="margin:0; padding:0;"' in sanitized_html
    assert 'margin:10px' not in sanitized_html  # Original bad style should be replaced
    assert 'border-collapse:collapse' in sanitized_html
    assert 'style="border:none;"' in sanitized_html
    assert 'border:1px solid black' not in sanitized_html


def test_sanitizer_preserves_structure():
    """Test that sanitizer preserves HTML structure while fixing styles."""

    test_html = """
    <table>
    <tr>
    <td style="border:1px solid black;">
    <a href="#" style="margin:10px;padding:5px;">Link</a>
    <img src="test.jpg" style="margin:20px;" alt="test">
    </td>
    </tr>
    </table>
    """

    sanitized = sanitize_email_html(test_html)

    # Structure should be preserved
    assert '<table' in sanitized  # Allow for attributes
    assert '<tr>' in sanitized
    assert '<td' in sanitized  # Allow for attributes
    assert '<a href="#"' in sanitized
    assert '<img src="test.jpg"' in sanitized
    assert 'alt="test"' in sanitized

    # Styles should be fixed
    assert 'style="border:none;"' in sanitized
    assert 'style="margin:0; padding:0;"' in sanitized
    assert 'style="border-collapse:collapse;"' in sanitized