name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, "release/**", "cherry/**", "chore/**", harden/**, fix/**, feat/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest ruff

      - name: Lint with ruff
        run: ruff check .

      - name: Run pytest
        env:
          PYTHONPATH: src
        run: pytest -q

      - name: Email guard (exports only)
        run: |
          python tools/email_guard.py --changed-only \
            --include "exports/**" \
            --include "dist/email/**" \
            --exclude "user_drafts/**" \
            --exclude "tmp/**"
